experiment_name: RSS_ToA_final


model:
  _target_: models.SwinUnet.Swin2D
  learning_rate: 1e-4
  swin:
    _target_: modules.swin_unet.SwinUnet
    img_size: 256
    patch_size: 4
    in_chans: 20 # 10 RSS + 10 ToA
    embed_dim: 48
    depths: [2, 2, 6, 2]
    decoder_depths: [2, 2, 6, 2]
    num_heads: [3, 6, 12, 24]
    window_size: 8
    mlp_ratio: 4.
    qkv_bias: True   
    qk_scale: null
    ape: False
    patch_norm: True
    final_upsample: "identity" 

train_dataloader:
  _target_: torch.utils.data.DataLoader
  batch_size: 128
  num_workers: 12
  pin_memory: True
  dataset:
    _target_: modules.loader_toa_test.locDL  
    phase: 'train'
    cityMap: False
    carsMap: False
    simulation: 'DPM'
    TxMaps: False
    return_dict: True
  

val_dataloader:
  _target_: torch.utils.data.DataLoader
  batch_size: 128
  num_workers: 12
  pin_memory: True
  dataset:
    _target_: modules.loader_toa_test.locDL  
    phase: 'test' # val
    cityMap: False
    carsMap: False
    simulation: 'DPM'
    TxMaps: False
    return_dict: True
  
test_dataloader:
  _target_: torch.utils.data.DataLoader
  batch_size: 128
  num_workers: 12
  pin_memory: True
  dataset:
    _target_: modules.loader_toa_test.locDL  
    phase: 'test'
    cityMap: False
    carsMap: False
    simulation: 'DPM'
    TxMaps: False
    return_dict: True
  
resume_path: null
gpus: null